app_deployment:
  appName: db-backup-service
  image: nexus-docker-craigmiller160.ddns.net/db-backup-service:latest
  configMap:
    db.postgres.host: postgres.infra-prod
    db.postgres.port: "5432"
    config.file: backup_config_prod.json
    output.root-directory: /output
    output.cleanup.age-days: "10"
    executor.interval-secs: "86400"
    email.host: https://email-service:8443
    mongodump.command: /mongotools/mongodump
    db.mongo.host: mongodb.infra-prod
    db.mongo.port: "27017"
    logger.application.level: info
    auth.host: https://auth-craigmiller160.ddns.net
    auth.realm: apps-prod
  onepassworditems:
    - name: db-backup-service-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
    - name: db-backup-service-mongodb
      itemPath: vaults/Home Server (Prod)/items/MongoDB Root Account
    - name: db-backup-service-oauth2
      itemPath: vaults/Home Server (Prod)/items/DB Backup Service OAuth2 Keys
  secrets:
    - envVariable: db.postgres.user
      secretName: db-backup-service-postgres
      secretKey: username
    - envVariable: db.postgres.password
      secretName: db-backup-service-postgres
      secretKey: password
    - envVariable: db.mongo.user
      secretName: db-backup-service-mongodb
      secretKey: username
    - envVariable: db.mongo.password
      secretName: db-backup-service-mongodb
      secretKey: password
    - envVariable: auth.client-id
      secretName: db-backup-service-oauth2
      secretKey: kcClientId
    - envVariable: auth.client-id
      secretName: db-backup-service-oauth2
      secretKey: kcClientSecret
  commonProbe:
    exec:
      command:
        - sh
        - /output/liveness.sh
  volumes:
    - name: db-backup-service-volume
      type: HostPath
      hostPath: /home/craig/OtherDrive/DbBackup
      deploymentMountPath: /output