version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: db_backup_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
  mongodb:
    image: mongo:6.0.1
    container_name: db_backup_mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password