apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup-service-configmap
data:
  db.postgres.host: postgres-service
  db.postgres.port: "5432"
  db.postgres.user: user
  db.postgres.password: password
  config.file: backup_config_prod.json
  # TODO work on the next property here
  output.root-directory: /output
  # TODO be sure to test it with a lower interval to ensure loop is working