apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup-service-configmap
data:
  db.postgres.host: postgres-service
  db.postgres.port: "5432"
  db.postgres.user: postgres_root
  config.file: backup_config_prod.json
  output.root-directory: /output
  output.cleanup.age-days: "30"
  executor.interval-secs: "3600"
  email.host: https://email-service-service:8443
  email.auth.host: https://sso-oauth2-server-service:8443
  email.auth.client-key: 17795450-ff0d-47fe-b23c-dfe6d7f090d8
  email.auth.user: dbBackupService@gmail.com
  email.auth.password: db-backup-service-2020
  mongodump.command: /mongotools/mongodump
  db.mongo.host: mongodb-service
  db.mongo.port: "27017"
  db.mongo.user: mongo_root
  logger.application.level: info