apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-backup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-backup-service
  template:
    metadata:
      labels:
        app: db-backup-service
    spec:
      containers:
        - name: db-backup-service
          image: craigmiller160.ddns.net:30004/db-backup-service:latest
          envFrom:
            - configMapRef:
                name: db-backup-service-configmap
          env:
            - name: db.postgres.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
            - name: db.mongo.password
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-password
                  key: MONGO_ROOT_PASSWORD
            - name: email.auth.client-secret
              valueFrom:
                secretKeyRef:
                  name: email-service-client-secret
                  key: client-secret
          volumeMounts:
            - mountPath: /output
              name: db-backup-service-volume
          # TODO how am I going to do this???
          livenessProbe:
            exec:
              command:
                - sh
                - /output/liveness.sh
            initialDelaySeconds: 60
            periodSeconds: 300
      volumes:
        - name: db-backup-service-volume
          hostPath:
            path: /opt/kubernetes/data/db-backup-service